COMP: correct MSVC error C2516 for ill formed class in ITK 5.3
Of course Microslop compiler does not work like other, thus we need to
apply an itk path